version: '3.9'
services:
  
  db:
    image: "postgres"
    ports:  ["5434:5432"]
    environment: 

        "POSTGRES_PASSWORD": "root"
        "POSTGRES_USER": "postgres"
        "POSTGRES_DB":  "Termini"

  server:
    build: .
    ports:  ["3000:3000"]
    depends_on:
      - db

nginx:
    image: nginx:latest
    ports:
      - "80:80"    # Map port 80 on the host to port 80 on the Nginx container
      - "443:443"  # Map port 443 on the host to port 443 on the Nginx container for HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount Nginx configuration
      - ./https:/etc/nginx/ssl             # Mount SSL certificates
    depends_on:
      - server  # Ensure the server container starts first

networks:
  default:
    external:
      name: bridge